SELECT DISTINCT
    EMAILADDR AS Customer_Email,
    ELMCODE AS Customer_Number,
    [NAME] AS Customer_Name,
    NULL AS Customer_Type,
    NULL AS Customer_Street_Address,
    NULL AS Customer_ZipCode,
    NULL AS [Customer_City],
    NULL AS [Customer_State],
    NULL AS [Customer_Country],
    NULL AS [Customer_Industry_Code],
    NULL AS [Customer_Industry_Desc],
    NULL AS [Customer_Store_Number],
    NULL AS [Customer_Credit_Manager],
    NULL AS [Customer_Credit_Rep],
    NULL AS [Customer_Sales_Rep],
    NULL AS [Customer_terms_code],
    NULL AS [Parent_Customer_Number],
    NULL AS [Parent_Customer_Name],
    NULL AS [is_deleted_ind],
    NULL AS [Prospect_Customer_Number],
    NULL AS [Prospect_Customer_Name],
    NULL AS Customer_Acquired_date,
    NULL AS Customer_Class,
    NULL AS Customer_Division,
    NULL AS Full_Name,
    NULL AS [Customer_Phone_Number],
    NULL AS First_Name,
    NULL AS Last_Name,
    'CODA' AS [Source_DB],
    'OAS_ELMADDRLIST' AS [Source_Table],
     GETDATE() AS Source_Timestamp,
    NULL AS Validated
FROM
        dbo.OAS_ELMADDRLIST